<a href="https://colab.research.google.com/github/ptkoo/2DPlotterFromImage/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The following tutorial is adapted from the official NumPy documentation: https://numpy.org/doc/stable/user/quickstart.html

## Installation

`pip install numpy`

In [ ]:
import numpy as np

np.__version__

'1.25.2'

In [ ]:
# Example with 1-D data
data = [1.0, 2.0, 3.0]
x = np.array(data)
print("Example with 1-D data")
print(x)

Example with 1-D data
[1. 2. 3.]


In [ ]:
# Example with 2-D data
data = [[1., 2., 3.], [4., 5., 6]]
x = np.array(data)
print("Example with 2-D data")
print(x)

Example with 2-D data
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Example with 3-D data
data = [[[1.,2.], [3.,4.]],
        [[5.,6.], [7.,8.]]]
x = np.array(data)
print("Example with 3-D data")
print(x)

Example with 3-D data
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


# Initialization

In [ ]:
x = np.arange(1, 7)
x

array([1, 2, 3, 4, 5, 6])

Initialize arrays of zeros or ones

In [ ]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x = np.zeros((2, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

Initialize randomly

In [ ]:
x = np.random.randn(2, 3)
x

array([[ 0.72918561, -0.29757776,  0.38572396],
       [ 0.36762073,  0.07881691, -0.37343284]])

# ndarray attributes

In [ ]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.shape

(2, 3)

In [ ]:
x.dtype

dtype('int64')

# Indexing

In [ ]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[0, 2]

3

In [ ]:
x[1, :]

array([4, 5, 6])

In [ ]:
x[0, 2:]

array([3])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[a < 5]

array([1, 2, 3, 4])

In [ ]:
a[a < 5]

array([1, 2, 3, 4])

# Operations

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

`Broadcasting` is an operation of matching the dimensions of differently shaped arrays in order to be able to perform further operations on those arrays

In [ ]:
y = x + 2  # broadcasting
y

array([[3, 4],
       [5, 6]])

In [ ]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
np.dot(x, x)

array([[ 7, 10],
       [15, 22]])

In [ ]:
A = np.arange(15,24).reshape(3,3)
B = np.arange(20,29).reshape(3,3)
print("A: ",A)
print("B: ",B)

# Multiply A and B
result = A.dot(B)
result

A:  [[15 16 17]
 [18 19 20]
 [21 22 23]]
B:  [[20 21 22]
 [23 24 25]
 [26 27 28]]


array([[1110, 1158, 1206],
       [1317, 1374, 1431],
       [1524, 1590, 1656]])

# Exercises:
1. Use the correct NumPy method to find all items with the value 4.
2. Select everything from (including) the third item to (not including) the fifth item from `np.array([10, 15, 20, 25, 30, 35, 40])`.
3. Use the correct NumPy method to return a sorted array.
4. Iterate and print elements in array `np.array([10, 15, 20, 25, 30, 35, 40])`
5. Play around with reshape method.
6. Stack 2 arrays vertically and horizontally. Try a different method from this notebook.

In [ ]:
Exercise: